import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';
import { cn } from '@/utils/cn';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          'flex h-[200vh] flex-col antialiased'
        )}
        data-theme="dark"
      >
        <a href="#main-content" className="sr-only">
          До головного контенту
        </a>
        <Header />
        <main className="grow" id="main-content">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
